Repository Team-Jag/Do-or-die-fitness-tracker, pull requests merged in 2020-04, with the labels that each got.

#26 Facial expression + Jumps delay
  m5/Main/Bean.h
  m5/Main/Campaign.h
  m5/Main/CampaignsView.h
  m5/Main/Main.ino
  m5/Main/TextBox.h
  m5/Main/TimeBar.h
  m5/Main/View.h
Labels: enhancement

#27 M5 campaigns
  m5/Main/Bean.h
  m5/Main/Campaign.h
  m5/Main/CampaignsView.h
  m5/Main/Main.ino
  m5/Main/View.h
Labels: enhancement

#30 Finished Campaigns, Improved Animations
  m5/Main/Bean.h
  m5/Main/CampaignsView.h
  m5/Main/Main.ino
  m5/Main/Pedometer.h
  m5/Main/TextBox.h
  m5/Main/TimeBar.h
  m5/Main/Timer.h
  m5/Main/View.h
Labels: bug, enhancement

#33 Create LICENSE
  LICENSE
Labels: documentation

#34 Stats View
  m5/Main/CampaignsView.h
  m5/Main/Main.ino
  m5/Main/StatsView.h
  m5/Main/TimeBar.h
  m5/Main/View.h
Labels: enhancement

#35 Improved Loading Screen
  m5/Main/Main.ino
  m5/Main/logo.c
  m5/Main/logo.png
Labels: enhancement

#37 Complete api features
  desktop/management_dashboard/data.pde
  desktop/management_dashboard/data/challenges.json
  desktop/management_dashboard/data/sponsors.json
  desktop/management_dashboard/data/users.json
  desktop/management_dashboard/events.pde
Labels: enhancement

#38 Updated desktop OOD and data persistence mechanism
  Portfolio/SystemDesign.md
Labels: documentation

#43 Original uml added
  Portfolio/Images/first_uml.png
Labels: documentation

#42 changed end-user story to be one user story
  Portfolio/SystemDesign.md
Labels: documentation

#65 Update user stories
  Portfolio/Images/user_gantt.png
  Portfolio/SystemDesign.md
  Portfolio/SystemImplementation.md
Labels: documentation

#66 Working practices
  Portfolio/Images/slack.png
  Portfolio/Images/weekly_meeting.png
  Portfolio/ProjectEvaluation.md
Labels: documentation

#67 M5 portfolio update
  Portfolio/Images/dotuml.png
  Portfolio/Images/m5uml.png
  Portfolio/SystemDesign.md
Labels: documentation

#69 Organise prototype (processing)
  Portfolio/M5StackPrototype/Button_c.pde
  Portfolio/M5StackPrototype/HOME.png
  Portfolio/M5StackPrototype/HOME.svg
  Portfolio/M5StackPrototype/HOMEHAT.png
  Portfolio/M5StackPrototype/HOMEHAT.svg
  Portfolio/M5StackPrototype/M5StackPrototype.pde
  Portfolio/M5StackPrototype/SHOP.png
  Portfolio/M5StackPrototype/SHOP.svg
  Portfolio/M5StackPrototype/STATS.png
  Portfolio/M5StackPrototype/STATS.svg
  Portfolio/M5StackPrototype/Timer_c.pde
  Portfolio/M5StackPrototype/view.pde
Labels: organisation

#70 Implemented Push/Pull mechanism for Campaigns
  m5/Main/CampaignsView.h
  m5/Main/Main.ino
  m5/Main/StatsView.h
Labels: bug, enhancement

#73 Turned Epoch time into DateTime
  m5/Main/CampaignsView.h
  m5/Main/Main.ino
Labels: enhancement

#76 move the video
  Portfolio/SystemDesign.md
Labels: documentation-fix

#78 M5 portfolio
  Portfolio/Images/designSpace.JPG
  Portfolio/Images/paperPrototype.JPG
  Portfolio/Images/userTesting.JPG
  Portfolio/SystemDesign.md
Labels: documentation

#79 Fixed sponsor api not found
  desktop/management_dashboard/management_dashboard.pde
Labels: enhancement

#84 M5 sprints
  Portfolio/SystemImplementation.md
Labels: documentation, documentation-fix

#88 added push user stats request
  desktop/management_dashboard/data.pde
  desktop/management_dashboard/data/users.json
  desktop/management_dashboard/events.pde
  desktop/management_dashboard/management_dashboard.pde
Labels: enhancement

#87 Updated social/ethical implications
  Portfolio/SystemImplementation.md
Labels: documentation

#94 View cleanup+feature
  desktop/management_dashboard/events.pde
  desktop/management_dashboard/view.pde
Labels: enhancement

#92 Update Mqtt_request_types.txt
  Documentation/Mqtt_request_types.txt
Labels: enhancement

#95 Add gantt
  Portfolio/Images/updated_gantt.png
  Portfolio/SystemImplementation.md
Labels: documentation-fix

#96 Update architecture uml
  Portfolio/Images/architecture-UML.png
  Portfolio/Images/architecture.png
  Portfolio/SystemDesign.md
Labels: documentation-fix

#97 user stories in implementation
  Portfolio/SystemImplementation.md
Labels: documentation

#98 Desktop API features added
  Portfolio/SystemImplementation.md
Labels: documentation

#99 M5 communicat protocols
  Portfolio/SystemDesign.md
Labels: documentation

#100 fixed encapsulation of database object
  desktop/management_dashboard/data.pde
  desktop/management_dashboard/data/users.json
  desktop/management_dashboard/management_dashboard.pde
Labels: enhancement

#102 Update working practices
  Portfolio/Images/groupMeetings.JPG
  Portfolio/ProjectEvaluation.md
Labels: documentation-fix

#107 Update SystemImplementation.md
  Portfolio/SystemImplementation.md
Labels: documentation

#109 links to kanban boards
  Portfolio/ProjectEvaluation.md
Labels: documentation-fix

#108 minor updates with links to the Kanban board
  Portfolio/SystemImplementation.md
Labels: documentation-fix

#111 Oop writeup m5
  Portfolio/Images/M5_UML.png
  Portfolio/SystemDesign.md
Labels: documentation

#110 fixed challenge error
  desktop/management_dashboard/data.pde
  desktop/management_dashboard/data/challenges.json
  desktop/management_dashboard/data/sponsors.json
  desktop/management_dashboard/data/users.json
  desktop/management_dashboard/management_dashboard.pde
Labels: enhancement

#114 Architecture update
  Portfolio/SystemDesign.md
Labels: documentation

#117 Formatting and links
  Portfolio/SystemDesign.md
  Portfolio/SystemImplementation.md
Labels: documentation-fix

#118 Update group working
  Portfolio/Images/groupGithub.png
  Portfolio/ProjectEvaluation.md
Labels: documentation, documentation-fix

#130 fixed all relative links
  Portfolio/ProjectEvaluation.md
  Portfolio/SystemDesign.md
  Portfolio/SystemImplementation.md
  README.md
Labels: documentation-fix

#132 Future work
  Portfolio/Images/M5Images/M5Shop.jpg
  Portfolio/ProjectEvaluation.md
Labels: documentation

#133 Added LIbraries used in M5Stack
  README.md
Labels: documentation-fix

#116 Update ProjectEvaluation.md
  Portfolio/ProjectEvaluation.md
Labels: documentation-fix
