Repository Team-Jag/Do-or-die-fitness-tracker, pull requests merged in 2020-05, with the labels that each got.

#135 updated system design and implementation
  Portfolio/SystemDesign.md
  Portfolio/SystemImplementation.md
Labels: documentation

#136 Add intro portfolio
  Portfolio/ProjectEvaluation.md
  Portfolio/SystemDesign.md
  Portfolio/SystemImplementation.md
  README.md
Labels: documentation-fix

#138 Update architecture
  Portfolio/SystemDesign.md
Labels: documentation-fix

#141 system design restructure
  Portfolio/SystemDesign.md
Labels: documentation-fix

#143 M5 object oriented
  Portfolio/SystemDesign.md
  Portfolio/SystemImplementation.md
Labels: documentation-fix

#144 added analysis of user stories implemented
  Portfolio/SystemImplementation.md
Labels: documentation

#148 Ui wireframes introduction
  Portfolio/Images/prototype.gif
  Portfolio/Images/userTestingUpdated.png
  Portfolio/SystemDesign.md
Labels: documentation-fix

#149 System design conclusion
  Portfolio/SystemDesign.md
Labels: documentation-fix

#152 project evaluation update
  Portfolio/ProjectEvaluation.md
  README.md
Labels: documentation-fix

#155 Sequence
  Documentation/mission distinction-2.pdf
  Portfolio/Images/sequence.png
  Portfolio/Images/userSequence.png
  Portfolio/SystemDesign.md
Labels: documentation-fix

#154 web edits
  Portfolio/ProjectEvaluation.md
  Portfolio/SystemDesign.md
  Portfolio/SystemImplementation.md
Labels: documentation, documentation-fix

#160 sprint 5 intro and reflections
  Portfolio/SystemImplementation.md
Labels: documentation-fix

#163 added more analysis, fixed minor grammar formatting issues
  Portfolio/SystemImplementation.md
Labels: documentation-fix

#165 object oriented
  Portfolio/SystemDesign.md
Labels: documentation, documentation-fix

#168 Amy updates
  Portfolio/Images/invertedLogo.png
  README.md
Labels: documentation, portfolio-enhancement

#174 Amy read me update
  README.md
Labels: documentation-enhancement

#175 update video link
  Portfolio/SystemDesign.md
Labels: documentation-fix

#176 update jot notes
  Portfolio/SystemDesign.md
  Portfolio/SystemImplementation.md
Labels: documentation-fix

#184 minor updates including mario
  Portfolio/SystemDesign.md
  Portfolio/SystemImplementation.md
  README.md
Labels: documentation-enhancement

#185 Design update
  Portfolio/SystemDesign.md
  Portfolio/SystemImplementation.md
Labels: documentation-enhancement

#186 Sprint update
  Portfolio/SystemImplementation.md
Labels: documentation-fix

#187 gif added to main page
  Portfolio/Images/product.gif
  README.md
Labels: documentation-enhancement

#188 Main page update
  README.md
Labels: documentation-enhancement

#189 updated sprints
  Portfolio/SystemImplementation.md
Labels: documentation-enhancement

#190 Update README.md
  README.md
Labels: documentation-fix

#191 system imp update
  Portfolio/Images/waterfallagile.png
  Portfolio/ProjectEvaluation.md
  Portfolio/SystemDesign.md
  Portfolio/SystemImplementation.md
Labels: documentation-enhancement

#197 add video links
  README.md
Labels: documentation-enhancement

#200 Reword
  Portfolio/SystemDesign.md
  README.md
Labels: documentation-error, documentation-fix

#201 Amy final
  Portfolio/ProjectEvaluation.md
Labels: documentation-fix

#202 update persona cards
  Portfolio/Images/AMITA.png
  Portfolio/Images/mario.png
  Portfolio/Images/sponsortemplate.png
Labels: documentation-enhancement

#203 Amy edits
  Portfolio/ProjectEvaluation.md
  Portfolio/SystemDesign.md
  Portfolio/SystemImplementation.md
Labels: documentation-fix

#204 Grammar updates
  Portfolio/SystemDesign.md
Labels: documentation-fix

#205 Gif
  Portfolio/Images/main.gif
  Portfolio/Images/main2.gif
  README.md
Labels: documentation-enhancement

#206 system design grammar
  Portfolio/SystemDesign.md
Labels: documentation-fix

#207 amy says bye to GitHub
  Portfolio/SystemImplementation.md
Labels: documentation-enhancement
